services:
  sub-si:
    build:
      context: .
    image: sub-si:0.1.8
    container_name: sub-si
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80"
    labels:
      - "tainn.type=app"
      - "traefik.enable=true"
      - "traefik.http.routers.self.rule=Host(`self.dev.sub.si`)"
      - "traefik.http.routers.self.entrypoints=websecure"
      - "traefik.http.routers.self.tls.certresolver=self"
      - "traefik.http.services.self.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
