services:
  sub-si:
    build:
      context: .
    image: sub-si:0.1.6
    container_name: sub-si
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80"
    labels:
      - "type=app"
      - "traefik.enable=true"
      - "traefik.http.routers.sub-si.rule=Host(`sub.si`)"
      - "traefik.http.routers.sub-si.entrypoints=websecure"
      - "traefik.http.routers.sub-si.tls.certresolver=root"
      - "traefik.http.services.sub-si.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
