services:
  sub-si:
    build:
      context: .
    image: sub-si:0.1.12
    container_name: sub-si
    restart: unless-stopped
    networks:
      - ext
    ports:
      - "80"
    labels:
      - "tainn.type=app"
      - "traefik.enable=true"
      - "traefik.http.routers.root.rule=Host(`sub.si`)"
      - "traefik.http.routers.root.entrypoints=websecure"
      - "traefik.http.routers.root.tls.certresolver=root"
      - "traefik.http.services.root.loadbalancer.server.port=80"

networks:
  ext:
    external: true
